### ISSUE TITLE
ImportError: cannot import name 'GeoJSONSource' from 'geobeam.io'

### ISSUE THREAD

**Issue by migaelhartzenberg** [GoogleCloudPlatform/dataflow-geobeam#28] opened 2022-03-04 13:20 UTC
I am fairly new to python and Apache beam, however, I used the `shapefile_nfhl.py` as an example to create a reader for GeoJSON files, therefore I imported the `GeoJSONSource` (as per documentation) from geobeam.io but when I run the application I get the following error `ImportError: cannot import name 'GeoJSONSource' from 'geobeam.io' ` 

Am I missing something as I did follow the instructions to install geobeam. `pip install geobeam`

I have tried this with python 3.7, 3.9 and 3.10, versions 3.7 and 3.9 gives this error where as 3.10 does not work at all - getting issues while installing rasterio.

I am also running this on macOS Monterey (12.2.1)

Here is my code:
```python 
def run(pipeline_args, known_args): 
    import apache_beam as beam
    from apache_beam.io.gcp.internal.clients import bigquery as beam_bigquery
    from apache_beam.options.pipeline_options import PipelineOptions, SetupOptions
    from geobeam.io import GeoJSONSource
    from geobeam.fn import format_record, make_valid, filter_invalid

    pipeline_options = PipelineOptions([
        '--experiments', 'use_beam_bq_sink',
    ] + pipeline_args)

    with beam.Pipeline(options=pipeline_options) as p:
        (p
         | beam.io.Read(GeoJSONSource(known_args.gcs_url,
             layer_name=known_args.layer_name))
         | 'MakeValid' >> beam.Map(make_valid)
         | 'FilterInvalid' >> beam.Filter(filter_invalid)
         | 'FormatRecords' >> beam.Map(format_record)
         | 'WriteToBigQuery' >> beam.io.WriteToBigQuery(
             beam_bigquery.TableReference(
                 datasetId=known_args.dataset,
                 tableId=known_args.table),
             method=beam.io.WriteToBigQuery.Method.FILE_LOADS,
             write_disposition=beam.io.BigQueryDisposition.WRITE_TRUNCATE,
             create_disposition=beam.io.BigQueryDisposition.CREATE_NEVER))


if __name__ == '__main__':
    import logging
    import argparse

    logging.getLogger().setLevel(logging.INFO)

    parser = argparse.ArgumentParser()
    parser.add_argument('--gcs_url')
    parser.add_argument('--dataset')
    parser.add_argument('--table')
    parser.add_argument('--layer_name')
    parser.add_argument('--in_epsg', type=int, default=None)
    known_args, pipeline_args = parser.parse_known_args()

    run(pipeline_args, known_args)```

**Comment by tjwebb** [comment] 2022-03-07 16:38
Thanks for the issue, I'll take a look this week.

**Comment by tjwebb** [comment] 2022-03-07 16:40
possible dupe of #19

**Comment by migaelhartzenberg** [comment] 2022-03-08 11:54
> possible dupe of #19

I saw this issue, but since they mentioned `...no attribute` I thought it can be a different issue.

**Closed** 2022-03-09 05:47 UTC
